apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: linux-skill-assessment-role
  namespace: faslasherin-dev
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
  - watch
