apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      toolchain.dev.openshift.com/last-applied-configuration: '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"labels":{"toolchain.dev.openshift.com/provider":"codeready-toolchain","toolchain.dev.openshift.com/space":"faslasherin"},"name":"exec-pods","namespace":"faslasherin-dev"},"rules":[{"apiGroups":[""],"resources":["pods/exec"],"verbs":["get","list","watch","create","delete","update"]}]}'
    creationTimestamp: "2026-09-09T08:56:05Z"
    labels:
      toolchain.dev.openshift.com/provider: codeready-toolchain
      toolchain.dev.openshift.com/space: faslasherin
    name: exec-pods
    namespace: faslasherin-dev
    resourceVersion: "6073571157"
    uid: 6d322e38-e15a-4077-b772-2335362d66a7
  rules:
  - apiGroups:
    - ""
    resources:
    - pods/exec
    verbs:
    - get
    - list
    - watch
    - create
    - delete
    - update
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    creationTimestamp: "2026-09-11T06:45:12Z"
    name: linux-skill-assessment-role
    namespace: faslasherin-dev
    resourceVersion: "6082611296"
    uid: 918b0967-97f1-419d-a2a2-df7dc2c363a2
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - services
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      toolchain.dev.openshift.com/last-applied-configuration: '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"labels":{"toolchain.dev.openshift.com/provider":"codeready-toolchain","toolchain.dev.openshift.com/space":"faslasherin"},"name":"rbac-edit","namespace":"faslasherin-dev"},"rules":[{"apiGroups":["authorization.openshift.io","rbac.authorization.k8s.io"],"resources":["roles","rolebindings"],"verbs":["get","list","watch","create","update","patch","delete"]}]}'
    creationTimestamp: "2026-09-09T08:56:06Z"
    labels:
      toolchain.dev.openshift.com/provider: codeready-toolchain
      toolchain.dev.openshift.com/space: faslasherin
    name: rbac-edit
    namespace: faslasherin-dev
    resourceVersion: "6073571275"
    uid: fbc13bba-7816-41d7-9610-21165859ece3
  rules:
  - apiGroups:
    - authorization.openshift.io
    - rbac.authorization.k8s.io
    resources:
    - roles
    - rolebindings
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
kind: List
metadata:
  resourceVersion: ""
