apiVersion: v1
kind: ServiceAccount
metadata:
  name: linux-skill-assessment-sa
  namespace: faslasherin-dev
imagePullSecrets:
- name: linux-skill-assessment-sa-dockercfg-zvrwr
secrets:
- name: linux-skill-assessment-sa-dockercfg-zvrwr
